--- 
- name: Configure server 2 containers
  hosts: best_server_2
  user: ec2-user
  gather_facts: false
  vars_files:
    host_vars/hosts.yml

  tasks:
    - name: Copy variables.env to best_server_2.
      ansible.builtin.copy:
        src: ../../variables.env
        dest: ~/variables.env

    - name: Create docker network.
      community.docker.docker_network:
        name: cart-network

    - name: Create docker cart service.
      community.docker.docker_container:
        name: cartservice
        image: public.ecr.aws/j1n2c2p2/microservices-demo/cartservice:latest
        env_file: variables.env
        env:
          PORT: "7070"
        network_mode: cart-network
        ports:
          - "7070:7070"
        auto_remove: true
        state: started

    - name: Create docker shipping service
      community.docker.docker_container:
        name: shippingservice
        image: public.ecr.aws/j1n2c2p2/microservices-demo/shippingservice:latest
        env_file: variables.env
        env:
          PORT: "50051"
        network_mode: cart-network
        ports:
          - "50051:50051"
        auto_remove: true
        state: started

    - name: Create docker currency service
      community.docker.docker_container:
        name: currencyservice
        image: public.ecr.aws/j1n2c2p2/microservices-demo/currencyservice:latest
        env_file: variables.env
        env:
          PORT: "7000"
        network_mode: cart-network
        ports:
          - "7000:7000"
          - "60000:60000"
          - "50000:50000"
        auto_remove: true
        state: started