---
- name: Configure server 3 containers
  hosts: best_server_3
  user: ec2-user
  gather_facts: false
  vars_files:
    host_vars/hosts.yml

  tasks:
    - name: Copy variables.env to best_server_3.
      ansible.builtin.copy:
        src: ../../variables.env
        dest: ~/variables.env

    - name: Create docker network.
      community.docker.docker_network:
        name: checkout-network
   
# Create all the docker services for this server

    - name: Create docker checkout service.
      community.docker.docker_container:
        name: checkoutservice
        image: public.ecr.aws/j1n2c2p2/microservices-demo/checkoutservice:latest
        env_file: variables.env
        env:
          PORT: "5050"
        network_mode: checkout-network
        ports:
          - "5050:5050"
        etc_hosts: 
          productcatalogservice: "{{ server1 }}"
          cartservice: "{{ server2 }}"
          shippingservice: "{{ server2 }}"
          currencyservice: "{{ server2 }}"
        auto_remove: true
        state: started

    - name: Create docker payment service
      community.docker.docker_container:
        name: paymentservice
        image: public.ecr.aws/j1n2c2p2/microservices-demo/paymentservice:latest
        env_file: variables.env
        env:
          PORT: "50051"
        network_mode: checkout-network
        ports:
          - "50051:50051"
        auto_remove: true
        state: started
    
    - name: Create docker email service
      community.docker.docker_container:
        name: emailservice
        image: public.ecr.aws/j1n2c2p2/microservices-demo/emailservice:latest
        env_file: variables.env
        env:
          PORT: "5000"
        network_mode: checkout-network
        ports:
          - "5000:5000"
        auto_remove: true
        state: started