- name: Get private IP addresses of best-servers
  hosts: localhost
  gather_facts: no
  vars:
    servers:
      - best-server-1
      - best-server-2
      - best-server-3
      - best-server-4

  tasks:
    - name: Get private IP addresses of best-servers
      ec2_instance_info:
        region: us-east-1
        # credentials toevoegen
        filters:
          "tag:Name": "{{ item }}"
      loop: "{{ servers }}"
      register: ec2_info

    - name: Set private IP addresses into a variable
      set_fact:
        private_ips: "{{ private_ips | default([]) + [item.instances[0].private_ip_address] }}"
      loop: "{{ ec2_info.results }}"
      when: item.instances | length > 0

    - name: Save private IP addresses to ips-file
      copy:
        content: "{{ private_ips | join('\n') }}"
        dest: ips
