---
- name: Get Private IP Addresses of EC2 Instances
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Gather EC2 Instances Information
      community.aws.ec2_instance_info:
        profile: "automation"
        region: "us-east-1" 
      register: ec2_instances

    - name: Extract Private IP Addresses
      set_fact:
        private_ip_addresses: "{{ ec2_instances.instances | map(attribute='private_ip_address') | list }}"

    - name: Display Private IP Addresses
      debug:
        var: private_ip_addresses
