- name: Run Docker containers on best-server2
  hosts: best-server2
  become: yes
  user: ec2-user
  tasks:
    - name: Create Docker network
      docker_network:
        name: cart-network
      ignore_errors: yes

    - name: Copy variables.env to server
      copy:
        src: variables.env
        dest: ~/variables.env

    - name: Run cartservice container
      docker_container:
        name: cartservice
        image: public.ecr.aws/j1n2c2p2/microservices-demo/cartservice:latest
        env:
          PORT: "7070"
        env_file: ~/variables.env
        network_mode: cart-network
        published_ports: "7070:7070"
        state: started

    - name: Run shippingservice container
      docker_container:
        name: shippingservice
        image: public.ecr.aws/j1n2c2p2/microservices-demo/shippingservice:latest
        env:
          PORT: "50051"
        env_file: ~/variables.env
        network_mode: cart-network
        published_ports: "50051:50051"
        state: started

    - name: Run currencyservice container
      docker_container:
        name: currencyservice
        image: public.ecr.aws/j1n2c2p2/microservices-demo/currencyservice:latest
        env:
          PORT: "7000"
        env_file: ~/variables.env
        network_mode: cart-network
        published_ports: "50000:50000"
        state: started
